// design/montage.tokens.json → src/styles/tokens.css
// Colors: light on :root, dark on [data-theme="dark"]. Type styles become classes (.title1, …).
import { readFile, writeFile } from 'node:fs/promises';

const SRC = new URL('../design/montage.tokens.json', import.meta.url);
const OUT = new URL('../src/styles/tokens.css', import.meta.url);

const tokens = JSON.parse(await readFile(SRC, 'utf8'));

// A token leaf has a $type; everything else is a group.
const isLeaf = (node) => node && typeof node === 'object' && '$type' in node;
const leaves = (node, path = []) =>
  Object.entries(node).flatMap(([key, child]) =>
    isLeaf(child) ? [[[...path, key], child]] : leaves(child, [...path, key]),
  );

// Custom property names cannot hold a bare '.', so spacing-0.5 becomes spacing-0\.5.
const cssName = (name) => name.replace(/\./g, '\\.');
const decl = (name, value) => `  --${cssName(name)}: ${value};`;
const byNumber = (entries) => [...entries].sort(([a], [b]) => Number(a) - Number(b));

// { value, ref } → var(--atomic-…). A ref with alpha is translucent: keep its computed hex.
const valueFor = ({ value, ref, alpha }) =>
  ref && alpha === undefined ? `var(--${ref.replace(/\./g, '-')})` : value;

const light = [];
const dark = [];

// atomic: theme-independent palette
for (const [hue, steps] of Object.entries(tokens.color.atomic)) {
  for (const [step, t] of byNumber(Object.entries(steps))) {
    light.push(decl(`atomic-${hue}-${step}`, t.light.value));
  }
}

// semantic: per theme
for (const [path, t] of leaves(tokens.color.semantic)) {
  const name = `semantic-${path.join('-')}`;
  light.push(decl(name, valueFor(t.light)));
  dark.push(decl(name, valueFor(t.dark)));
}

// effect.platform.ios.navigation: a composite of background color and backdrop filter
for (const [path, t] of leaves(tokens.effect.platform)) {
  const name = `platform-${path.join('-')}`;
  light.push(decl(name, t.light.backgroundColor), decl(`${name}-backdrop-filter`, t.light.backdropFilter));
  dark.push(decl(name, t.dark.backgroundColor), decl(`${name}-backdrop-filter`, t.dark.backdropFilter));
}

// shadows: semantic.elevation.shadow.<kind>.<size>
for (const [path, t] of leaves(tokens.shadow)) {
  const name = `semantic-elevation-shadow-${path.join('-')}`;
  light.push(decl(name, t.light.value));
  dark.push(decl(name, t.dark.value));
}

// theme-independent scales. radius keys are px values, plus 50pct for 50%.
const scales = [];
for (const [k, t] of byNumber(Object.entries(tokens.spacing))) scales.push(decl(`spacing-${k}`, t.value));
const radius = Object.entries(tokens.radius);
for (const [k, t] of byNumber(radius.filter(([k]) => !Number.isNaN(Number(k))))) scales.push(decl(`radius-${k}`, t.value));
for (const [k, t] of radius.filter(([k]) => Number.isNaN(Number(k)))) scales.push(decl(`radius-${k}`, t.value));
for (const [k, t] of byNumber(Object.entries(tokens.opacity))) scales.push(decl(`opacity-${k}`, t.value));
for (const [k, t] of Object.entries(tokens.breakpoint)) scales.push(decl(`breakpoint-${k}`, t.value));
for (const [k, t] of Object.entries(tokens.zIndex)) scales.push(decl(`z-index-${k}`, t.value));

// typography
// The token names only the family. A generic fallback keeps text sans-serif where Pretendard JP is not loaded.
const { fontFamily, fontWeight, variant } = tokens.typography;
scales.push(decl('font-sans', `'${fontFamily.value}', sans-serif`));
scales.push(decl('font-weight-regular', fontWeight.regular.value));
scales.push(decl('font-weight-medium', fontWeight.medium.value));
scales.push(decl('font-weight-bold', fontWeight.bold.value));

const typeClasses = Object.entries(variant).map(
  ([name, v]) =>
    `.${name} {\n  font-size: ${v.fontSize.rem};\n  line-height: ${v.lineHeight.rem};\n  letter-spacing: ${v.letterSpacing.em};\n}`,
);
const large = fontWeight.bold.largeVariants;
const weightClasses = [
  `.regular {\n  font-weight: ${fontWeight.regular.value};\n}`,
  `.medium {\n  font-weight: ${fontWeight.medium.value};\n}`,
  `.bold {\n  font-weight: ${fontWeight.bold.value};\n}`,
  `${large.map((n) => `.${n}.bold`).join(',\n')} {\n  font-weight: ${fontWeight.bold.valueForLargeVariants};\n}`,
];

const css = `/* Generated by scripts/build-tokens.mjs from design/montage.tokens.json. Do not edit; run \`npm run tokens\`. */

:root {
  color-scheme: light;
${light.join('\n')}
}

[data-theme="dark"] {
  color-scheme: dark;
${dark.join('\n')}
}

:root {
${scales.join('\n')}
}

/* Typography: size, line height and letter spacing per variant (rem 값이 원본, 루트 ${tokens.$meta.remBase}px 기준) */
${typeClasses.join('\n\n')}

/* Weights: bold is ${fontWeight.bold.value}, and ${fontWeight.bold.valueForLargeVariants} on ${large.join(', ')} */
${weightClasses.join('\n\n')}
`;

await writeFile(OUT, css);

const count = (lines) => lines.filter((l) => l.startsWith('  --')).length;
console.log(
  `src/styles/tokens.css: ${count(light)} light, ${count(dark)} dark, ${count(scales)} scale variables, ${typeClasses.length} type classes`,
);
